services:
  # Serviço do Banco de Dados Postgres
  db:
    image: postgres:17
    container_name: postgres_webscrapper_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Serviço da API do FastAPI
  api:
    build: .
    container_name: fastapi_webscrapper_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}  
      - DB_PORT=5432 
      - DB_NAME=${DB_NAME}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
    depends_on:
      - db

  scheduler:
    build: .
    container_name: webscrapper_scheduler
    command: python -m app.scheduler.scheduler
    restart: always
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
    depends_on:
      - db

volumes:
  postgres_data:

  